[package]
name = "orbcue-connect"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
orbcue-ipc = { path = "../dock-ipc" }
serde.workspace = true
serde_json.workspace = true

[target.'cfg(windows)'.dependencies]
windows-registry = "0.5"

