"""One-time, revocable connection of already-installed Agents.

The manager only discovers executables through PATH and writes user-level
wrapper scripts or native hook entries.  It never downloads, reinstalls, or
replaces an Agent executable.
"""
from __future__ import annotations

import json
import os
import shutil
import sys
import textwrap
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any, Optional

from .native_hooks import (
    CLAUDE_HOOK_ACTION,
    install_claude_hooks,
    uninstall_claude_hooks,
)

KNOWN_AGENTS = ("codex", "claude", "dsh")
PREFERRED_METHOD = {
    "codex": "wrapper",
    "claude": "native_hook",
    "dsh": "wrapper",
}
WRAPPER_LIMITATION = (
    "command wrapper reports start/stop/error only; it cannot detect "
    "waiting-for-input without a native Hook"
)
NATIVE_LIMITATION = (
    "native hooks report session start, permission/waiting, normal end, and "
    "failure; no transcript or terminal content is read"
)
PATH_BLOCK_START = "# >>> agent-activity-dock PATH >>>"
PATH_BLOCK_END = "# <<< agent-activity-dock PATH <<<"


@dataclass(frozen=True, slots=True)
class DiscoveredAgent:
    name: str
    path: str


@dataclass(frozen=True, slots=True)
class ConnectionRecord:
    name: str
    original: str
    method: str
    wrapper: Optional[str] = None
    hook_script: Optional[str] = None
    capabilities: tuple[str, ...] = ()
    limitation: str = ""
    installed_at: str = ""

    def to_dict(self) -> dict:
        value = asdict(self)
        value["capabilities"] = list(self.capabilities)
        return value

    @classmethod
    def from_dict(cls, value: dict) -> "ConnectionRecord":
        return cls(
            name=str(value["name"]),
            original=str(value["original"]),
            method=str(value["method"]),
            wrapper=value.get("wrapper"),
            hook_script=value.get("hook_script"),
            capabilities=tuple(value.get("capabilities", ())),
            limitation=str(value.get("limitation", "")),
            installed_at=str(value.get("installed_at", "")),
        )


@dataclass(frozen=True, slots=True)
class SetupResult:
    name: str
    status: str
    detail: str = ""


@dataclass(frozen=True, slots=True)
class SetupPlan:
    name: str
    original: str
    method: str
    status: str  # "connect" or "keep"
    detail: str = ""

    def describe(self) -> str:
        if self.status == "keep":
            return f"keep existing {self.method} connection"
        if self.method == "wrapper":
            return (
                f"create {self.bin_dir / self.name} and prepend "
                f"{self.bin_dir} to PATH in user shell rc"
            )
        if self.method == "native_hook":
            return (
                f"add revocable {self.name} hook entries to user settings.json "
                f"and create {self.hook_dir / (self.name + '-hook.py')}"
            )
        return f"connect with method {self.method}"

    @property
    def bin_dir(self) -> Path:
        return Path(
            os.environ.get("XDG_DATA_HOME", str(Path.home() / ".local" / "share"))
        ) / "agent-activity-dock" / "bin"

    @property
    def hook_dir(self) -> Path:
        return Path(
            os.environ.get("XDG_CONFIG_HOME", str(Path.home() / ".config"))
        ) / "agent-activity-dock" / "hooks"


_WRAPPER_TEMPLATE = """\
#!/usr/bin/env python3
# Generated by Agent Activity Dock.  This wrapper calls the original Agent
# executable only; it sends explicit start/stop/error events and forwards
# signals.  It never reads commands, prompts, transcripts, or terminal output.
import json
import os
import signal
import subprocess
import sys
import time
import uuid

ORIGINAL = {original}
SOURCE = {source}
DOCK_CLI_CANDIDATES = {candidates_json}
FORWARDED_SIGNALS = tuple(
    getattr(signal, name) for name in ("SIGINT", "SIGTERM", "SIGHUP", "SIGQUIT")
    if hasattr(signal, name)
)


def emit(action, task_id, terminal=None):
    event_id = f"{SOURCE}-{action}-{task_id}-{uuid.uuid4().hex}"
    argv = [
        action,
        task_id,
        "--source",
        SOURCE,
        "--event-id",
        event_id,
    ]
    if terminal:
        argv.extend(["--terminal", terminal])
    for candidate in DOCK_CLI_CANDIDATES:
        try:
            proc = subprocess.run(
                candidate + ["--json", "--timeout", "0.25"] + argv,
                stdin=subprocess.DEVNULL,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
                timeout=1.0,
            )
        except (OSError, subprocess.SubprocessError):
            continue
        if proc.returncode in (0, 1):
            return True
    return False


def main():
    task_id = (
        os.environ.get("AGENT_ACTIVITY_DOCK_TASK_ID")
        or os.environ.get("AADOCK_TASK_ID")
        or f"{SOURCE}-{os.getpid()}-{uuid.uuid4().hex[:10]}"
    )
    terminal = os.environ.get("AGENT_ACTIVITY_DOCK_TERMINAL") or os.environ.get(
        "AADOCK_TERMINAL"
    )
    emit("start", task_id, terminal)

    child = subprocess.Popen([ORIGINAL] + sys.argv[1:])
    old_handlers = {}
    for signum in FORWARDED_SIGNALS:
        old_handlers[signum] = signal.getsignal(signum)

    def forward(signum, frame):  # noqa: ARG001
        if child.poll() is None:
            child.send_signal(signum)

    for signum in FORWARDED_SIGNALS:
        signal.signal(signum, forward)

    returncode = child.wait()
    for signum, handler in old_handlers.items():
        signal.signal(signum, handler)

    emit("error" if returncode != 0 else "stop", task_id, terminal)

    if returncode < 0:
        signum = -returncode
        signal.signal(signum, signal.SIG_DFL)
        os.kill(os.getpid(), signum)
        time.sleep(0.2)
        os._exit(128 + signum)
    if returncode >= 128 and (returncode - 128) in FORWARDED_SIGNALS:
        signum = returncode - 128
        signal.signal(signum, signal.SIG_DFL)
        os.kill(os.getpid(), signum)
        time.sleep(0.2)
        os._exit(returncode)
    raise SystemExit(returncode if 0 <= returncode <= 255 else 1)


if __name__ == "__main__":
    main()
"""

_HOOK_SCRIPT_TEMPLATE = """\
#!/usr/bin/env python3
# Generated by Agent Activity Dock.  Reads only Claude's structured hook JSON
# from stdin and emits the matching lifecycle event.  It deliberately never
# opens transcript_path, tool input, prompts, or terminal output.
import json
import os
import subprocess
import sys
import uuid

SOURCE = "claude"
DOCK_CLI_CANDIDATES = {candidates_json}
ACTION_BY_EVENT = {action_map}


def emit(action, task_id):
    event_id = f"claude-{action}-{task_id}-{uuid.uuid4().hex}"
    argv = [
        action,
        task_id,
        "--source",
        SOURCE,
        "--event-id",
        event_id,
    ]
    for candidate in DOCK_CLI_CANDIDATES:
        try:
            proc = subprocess.run(
                candidate + ["--json", "--timeout", "0.25"] + argv,
                stdin=subprocess.DEVNULL,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
                timeout=1.0,
            )
        except (OSError, subprocess.SubprocessError):
            continue
        if proc.returncode in (0, 1):
            return True
    return False


def main():
    try:
        payload = json.load(sys.stdin)
    except Exception:
        payload = {}
    if not isinstance(payload, dict):
        payload = {}
    event_name = payload.get("hook_event_name") or payload.get("hook_event")
    action = ACTION_BY_EVENT.get(event_name)
    if action is None:
        print("{}")
        return 0
    task_id = (
        payload.get("session_id")
        or os.environ.get("AGENT_ACTIVITY_DOCK_TASK_ID")
        or f"claude-{os.getpid()}-{uuid.uuid4().hex[:10]}"
    )
    emit(action, str(task_id))
    print("{}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
"""


class ConnectionManager:
    def __init__(self, dock_cli_candidates: list[list[str]] | None = None) -> None:
        home = Path(os.environ.get("HOME", str(Path.home())))
        config_home = Path(
            os.environ.get("XDG_CONFIG_HOME", str(home / ".config"))
        )
        data_home = Path(
            os.environ.get("XDG_DATA_HOME", str(home / ".local" / "share"))
        )
        self.home = home
        self.config_dir = config_home / "agent-activity-dock"
        self.bin_dir = data_home / "agent-activity-dock" / "bin"
        self.hook_dir = self.config_dir / "hooks"
        self.config_path = self.config_dir / "connections.json"
        self.dock_cli_candidates = (
            dock_cli_candidates or self._default_dock_cli_candidates()
        )
        self._data: dict[str, Any] = {"schema": 1, "agents": {}}
        self.load()

    @staticmethod
    def _default_dock_cli_candidates() -> list[list[str]]:
        candidates: list[list[str]] = [["dock"]]
        candidates.append([sys.executable, "-m", "agent_activity_dock.cli"])
        candidates.append(
            [sys.executable, str(Path(__file__).with_name("cli.py"))]
        )
        return candidates

    def load(self) -> "ConnectionManager":
        if self.config_path.exists():
            try:
                value = json.loads(self.config_path.read_text())
                if isinstance(value, dict) and isinstance(value.get("agents"), dict):
                    self._data = value
            except (OSError, json.JSONDecodeError):
                self._data = {"schema": 1, "agents": {}}
        return self

    def save(self) -> None:
        self.config_dir.mkdir(parents=True, exist_ok=True, mode=0o700)
        self.config_dir.chmod(0o700)
        tmp = self.config_path.with_suffix(".json.tmp")
        tmp.write_text(json.dumps(self._data, indent=2) + "\n")
        tmp.chmod(0o600)
        tmp.replace(self.config_path)
        self.config_path.chmod(0o600)

    @property
    def agents(self) -> dict[str, ConnectionRecord]:
        return {
            name: ConnectionRecord.from_dict(value)
            for name, value in self._data.get("agents", {}).items()
        }

    def record(self, name: str) -> Optional[ConnectionRecord]:
        value = self._data.get("agents", {}).get(name)
        return ConnectionRecord.from_dict(value) if value else None

    def discover_agents(self) -> list[DiscoveredAgent]:
        found = []
        for name in KNOWN_AGENTS:
            path = shutil.which(name)
            if path:
                found.append(DiscoveredAgent(name=name, path=path))
        return found

    def plan_setup(self) -> list[SetupPlan]:
        plans: list[SetupPlan] = []
        for discovered in self.discover_agents():
            existing = self.record(discovered.name)
            if existing is not None:
                plans.append(
                    SetupPlan(
                        name=discovered.name,
                        original=discovered.path,
                        method=existing.method,
                        status="keep",
                        detail=existing.method,
                    )
                )
                continue
            method = PREFERRED_METHOD[discovered.name]
            plans.append(
                SetupPlan(
                    name=discovered.name,
                    original=discovered.path,
                    method=method,
                    status="connect",
                    detail=method,
                )
            )
        return plans

    def setup_all(self, yes: bool = False) -> list[SetupResult]:
        results: list[SetupResult] = []
        for discovered in self.discover_agents():
            existing = self.record(discovered.name)
            if existing is not None:
                results.append(
                    SetupResult(discovered.name, "already_connected", existing.method)
                )
                continue
            try:
                self.connect(
                    discovered.name,
                    discovered.path,
                    method=PREFERRED_METHOD[discovered.name],
                )
            except Exception as exc:
                results.append(
                    SetupResult(discovered.name, "failed", str(exc))
                )
            else:
                results.append(
                    SetupResult(
                        discovered.name,
                        "connected",
                        PREFERRED_METHOD[discovered.name],
                    )
                )
        return results

    def connect(
        self,
        name: str,
        original: str | Path,
        method: Optional[str] = None,
    ) -> ConnectionRecord:
        method = method or PREFERRED_METHOD.get(name, "wrapper")
        original_path = Path(original).expanduser()
        if not original_path.exists():
            raise FileNotFoundError(
                f"refusing to connect {name}: original executable not found at {original_path}"
            )
        original_abs = str(original_path.absolute())
        existing = self.record(name)
        if existing is not None and existing.method == method:
            if existing.original == original_abs:
                return existing
            # The Agent executable moved (or PATH now resolves elsewhere).
            # Refresh the recorded path and, for wrappers, regenerate the
            # user-level wrapper so it still calls the real command.
            if method == "wrapper":
                self._install_wrapper(name, original_abs)
                record = ConnectionRecord(
                    name=name,
                    original=original_abs,
                    method=method,
                    wrapper=str(self.bin_dir / name),
                    capabilities=existing.capabilities,
                    limitation=existing.limitation,
                    installed_at=existing.installed_at,
                )
            else:
                record = ConnectionRecord(
                    name=name,
                    original=original_abs,
                    method=method,
                    hook_script=existing.hook_script,
                    capabilities=existing.capabilities,
                    limitation=existing.limitation,
                    installed_at=existing.installed_at,
                )
            self._data.setdefault("agents", {})[name] = record.to_dict()
            self.save()
            return record

        installed_at = _utc_now()
        if method == "native_hook":
            if name != "claude":
                raise ValueError(f"no native hook installer is available for {name}")
            hook_script = self._install_claude_native_hook()
            record = ConnectionRecord(
                name=name,
                original=original_abs,
                method=method,
                hook_script=str(hook_script),
                capabilities=("start", "stop", "waiting", "error"),
                limitation=NATIVE_LIMITATION,
                installed_at=installed_at,
            )
        elif method == "wrapper":
            wrapper = self._install_wrapper(name, original_abs)
            record = ConnectionRecord(
                name=name,
                original=original_abs,
                method=method,
                wrapper=str(wrapper),
                capabilities=("start", "stop", "error"),
                limitation=WRAPPER_LIMITATION,
                installed_at=installed_at,
            )
        else:
            raise ValueError(f"unsupported connection method: {method}")

        self._data.setdefault("agents", {})[name] = record.to_dict()
        if existing is not None and existing.method != method:
            # The new connection is already recorded above.  Clean the old
            # user-level artifacts best-effort so a failed cleanup never
            # blocks the newly selected adapter.
            try:
                self._remove_connection_artifacts(existing)
            except Exception:
                pass
            if existing.method == "wrapper":
                # A wrapper PATH snippet is only useful while a wrapper
                # connection exists.  The new record has already replaced the
                # old one, so remove the snippet when this was the last
                # wrapper.
                if not self._wrapper_records():
                    self._remove_path_snippet()
                    self._remove_empty_bin_dir()
        self.save()
        return record

    def disconnect(self, name: str) -> bool:
        existing = self.record(name)
        if existing is None:
            return False
        self._remove_connection_artifacts(existing)

        self._data.get("agents", {}).pop(name, None)
        if not self._wrapper_records():
            self._remove_path_snippet()
            self._remove_empty_bin_dir()
        self.save()
        return True

    @staticmethod
    def _remove_connection_artifacts(record: ConnectionRecord) -> None:
        if record.method == "wrapper" and record.wrapper:
            try:
                Path(record.wrapper).unlink()
            except FileNotFoundError:
                pass
        elif record.method == "native_hook" and record.hook_script:
            uninstall_claude_hooks(Path(record.hook_script))
            try:
                Path(record.hook_script).unlink()
            except FileNotFoundError:
                pass

    def _install_wrapper(self, name: str, original: str) -> Path:
        self.bin_dir.mkdir(parents=True, exist_ok=True, mode=0o700)
        self.bin_dir.chmod(0o700)
        wrapper = self.bin_dir / name
        if Path(original) == wrapper:
            raise ValueError(
                f"wrapper would replace the real {name} executable; refusing"
            )
        self._ensure_path_snippet()
        marker = "# Generated by Agent Activity Dock."
        if wrapper.exists() and marker not in wrapper.read_text():
            raise FileExistsError(
                f"refusing to overwrite non-Dock file at {wrapper}"
            )
        content = (
            _WRAPPER_TEMPLATE.replace("{original}", json.dumps(original))
            .replace("{source}", json.dumps(name))
            .replace("{candidates_json}", json.dumps(self.dock_cli_candidates))
        )
        wrapper.write_text(content)
        wrapper.chmod(0o755)
        return wrapper

    def _install_claude_native_hook(self) -> Path:
        self.hook_dir.mkdir(parents=True, exist_ok=True, mode=0o700)
        self.hook_dir.chmod(0o700)
        hook_script = self.hook_dir / "claude-hook.py"
        content = (
            _HOOK_SCRIPT_TEMPLATE.replace(
                "{candidates_json}", json.dumps(self.dock_cli_candidates)
            ).replace("{action_map}", json.dumps(CLAUDE_HOOK_ACTION))
        )
        hook_script.write_text(content)
        hook_script.chmod(0o700)
        install_claude_hooks(hook_script)
        return hook_script

    def _ensure_path_snippet(self) -> None:
        block = _path_block(self.bin_dir)
        candidates = [self.home / ".bashrc", self.home / ".profile"]
        regular_files = [path for path in candidates if path.is_file()]
        target = regular_files[0] if regular_files else self.home / ".profile"
        if target.is_dir():
            raise RuntimeError(
                f"cannot install PATH snippet: {target} is a directory"
            )
        text = target.read_text() if target.exists() else ""
        if PATH_BLOCK_START in text:
            return
        if text and not text.endswith("\n"):
            text += "\n"
        text += block
        target.write_text(text)
        if not regular_files:
            target.chmod(0o600)

    def _remove_path_snippet(self) -> None:
        for path in (self.home / ".bashrc", self.home / ".profile"):
            if not path.exists():
                continue
            text = path.read_text()
            start = text.find(PATH_BLOCK_START)
            if start == -1:
                continue
            end = text.find(PATH_BLOCK_END, start)
            if end == -1:
                continue
            end += len(PATH_BLOCK_END)
            text = text[:start] + text[end:]
            path.write_text(text)

    def _wrapper_records(self) -> list[ConnectionRecord]:
        return [
            record
            for record in self.agents.values()
            if record.method == "wrapper"
        ]

    def _remove_empty_bin_dir(self) -> None:
        try:
            self.bin_dir.rmdir()
        except OSError:
            pass


def _path_block(bin_dir: Path) -> str:
    return textwrap.dedent(
        f"""
        {PATH_BLOCK_START}
        case ":${{PATH}}:" in
          *:"{bin_dir}":*) ;;
          *) export PATH="{bin_dir}:${{PATH}}" ;;
        esac
        {PATH_BLOCK_END}
        """
    )


def _utc_now() -> str:
    from datetime import datetime, timezone

    return datetime.now(timezone.utc).isoformat(timespec="seconds")
